M48
; DRILL file {KiCad (6.0.5)} date Fri 24 Jun 2022 16:36:35 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-24T16:36:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X4.3112Y-4.4
X4.3112Y-4.4984
X4.5081Y-4.2031
X4.7049Y-4.4
X4.7049Y-4.4984
T0
M30
